[platformio]
default_envs = esp32_devkit

[env:esp32_devkit]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
lib_deps =
    adafruit/Adafruit GFX Library @ ^1.11.9
    adafruit/Adafruit ST7735 and ST7789 Library @ ^1.10.3
    roboticsbrno/ServoESP32 @ ^1.0.3

[env:esp32_cam]
platform = espressif32
board = esp32cam
framework = arduino
monitor_speed = 115200
board_build.f_flash = 80000000L
board_build.flash_mode = qio
